import './globals.css'
import '../app/copy.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
   title: 'Next.js',
   description: 'Generated by Next.js',
}

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html lang="en">
         <meta name="viewport" content="width=device-width, initial-scale=1" />
         <body className={inter.className}>{children}</body>
      </html>
   )
}
